### ISSUE TITLE
Unable to run it under macOS

### ISSUE THREAD

**Issue by siara-cc** [zserge/webview-python#2]
Hi,  Thank you for the webview implementation on go/c++/python.

On macOS 10.12.6, I tried to use `pip install webview` or `pip3 install webview`, it gives compilation error on webview.h.

So I cloned the repository and tried `pip setup.py install`, it again gave compilation error.  It seemed to me the webview.h is not the same as the one for go/c++, so I copied webview.h from there, resolved signature differences with webview.c, then it was successful.

But when I run sample code it gives runtime error:

```
2019-01-20 14:47:44.404 Python[14194:118019] *** NSForwarding: warning: object 0x7fa279c31240 of class '__WKPreferences' does not implement methodSignatureForSelector: -- trouble ahead
2019-01-20 14:47:44.404 Python[14194:118019] *** NSForwarding: warning: object 0x7fa279c31240 of class '__WKPreferences' does not implement doesNotRecognizeSelector: -- abort
Trace/BPT trap: 5
```

on the line `w = webview.WebView(width=320, height=240, title="Hello", url="https://google.com", resizable=True, debug=False)`

Is it possible to get it working?

**Comment by mgrzeszczak** [comment]
@siara-cc Did you get it to run?

**Comment by siara-cc** [comment]
I somehow seem to have got it run, but don't remember how!!  I think in addition to what I did above, I copied a sample from main repo and modified it.  I am attaching it here (rename it to py)
[main.txt](https://github.com/zserge/webview-python/files/2908502/main.txt)
Hope it works for you too..
